
from os import system, name
from time import sleep
def clear():
    if name == 'nt':
        _ = system('clear')
print("Remember to give yourself proper braking distance. ")
V = int(input("Please input velocity"))
B = int(input("Please input when you want your brakes to engage(The higher the number, the earlier you will start your brakes.):"))
if V in range (1,29):
    if B <2: 
        sleep(.5)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("          t848&*@ []  ")
        print("         )317h!#&([]  ")
        print("         rg234&*(*[]  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        print("You failed, even though your speed was low, you did not give enough time for the brakes to give negative acceleration on the car.")
        print("")
        print("No one will come to your funeral.")
        sleep(10)
        clear()
    else:
        sleep(.5)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.6)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.7)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.8)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.9)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        print("Nice job, your speed was low, and your brakes were too. The brakes force had enough time to put negative acceleration on your car.")
        print("")
        print("You live to see another day")
        sleep(10)
elif V in range (30,39):
    if B <4:
        sleep(.1)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("          t848&*@ []  ")
        print("         )317h!#&([]  ")
        print("         rg234&*(*[]  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        print("You failed,  ")
        print("")
        print("Your death was inevitable.")
        sleep(10)
        clear()
    else: 
        sleep(.1)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.1)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.2)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.3)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.4)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.6)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        print("Good job, your cars momentum was nuetralized by your brake with the time given.")
        print("")
        print("Even if you didnt live, its not like anyone would be sad.")
        sleep(10)
        clear()
elif V == 40: 
    sleep(.2)
    clear()
    print("  _____           []  ")
    print(" [][] [|          []  ")
    print(" L______}         []  ")
    print(" Oo   oO          []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("   _____          []  ")
    print("  [][] [|         []  ")
    print("  L______}        []  ")
    print("  Oo   oO         []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("    _____         []  ")
    print("   [][] [|        []  ")
    print("   L______}       []  ")
    print("   Oo   oO        []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("     _____        []  ")
    print("    [][] [|\      []  ")
    print("    L______}>     []  ")
    print("    Oo   oO/      []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("      _____\      []  ")
    print("     [][] [|\     []  ")
    print("     L______}>    []  ")
    print("     Oo   oO/     []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("       _____\     []  ")
    print("      [][] [|\    []  ")
    print("      L______}>   []  ")
    print("      Oo   oO/    []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("       ()()()     []  ")
    print("      ()()()()    []  ")
    print("      ()()()()    []  ")
    print("      ()()()()    []  ")
    print("0m________________50m")
    sleep(.6)
    clear()
    print("                  []  ")
    print("                  []  ")
    print("                  []  ")
    print("           ^+^+^+^[]  ")
    print("0m________________50m")
    sleep(2)
    clear()
    V2 = int(input("Please input velocity"))
    B2 = int(input("Please input when you want your brakes to engage(The higher the number, the earlier you will start your brakes.):"))
    sleep(.2)
    clear()
    print("  _____           []  ")
    print(" [][] [|          []  ")
    print(" L______}         []  ")
    print(" Oo   oO          []  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("   _____          []   ) ")
    print("  [][] [|         []     () ")
    print("  L______}        []  ()    )")
    print("  Oo   oO         []  (   )")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("   _____          []      ()  ")
    print("  [][] [|         []    () () ()  ")
    print("  L______}        []     ()() ()  ")
    print("  Oo   oO         []      () () ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("     _____        []   /_____   ")
    print("    [][] [|       []  /|] [][]  ")
    print("    L______}      [] <{______|  ")
    print("    Oo   oO       []  \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("      _____       []  /_____   ")
    print("     [][] [|      [] /|] [][]  ")
    print("     L______}     []<{______|  ")
    print("     Oo   oO      [] \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("       _____      [  /_____   ")
    print("      [][] [|     [ /|] [][]  ")
    print("      L______}    [<{______|  ")
    print("      Oo   oO     [ \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("        _____       /_____   ")
    print("       [][] [|     /|] [][]  ")
    print("       L______}   <{______|  ")
    print("       Oo   oO     \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("         _____     /_____   ")
    print("        [][] [|   /|] [][]  ")
    print("        L______} <{______|  ")
    print("        Oo   oO   \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("         _____    /_____   ")
    print("        [][] [|  /|] [][]  ")
    print("        L______}<{______|  ")
    print("        Oo   oO  \Oo   oO  ")
    print("0m________________50m")
    sleep(.2)
    clear()
    print("         1UG92@(!92n!)   ")
    print("        bhueW@()12`80@)`-  ")
    print("        *hw9H8!@h193189!@  ")
    print("        WSTRDTFYTUGYtw3e4  ")
    print("0m________________50m")
    print("Maybe dont play with time travel next time.")


elif V in range (60,101):
    if B <16: 
        sleep(.05)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("          t848&*@ []  ")
        print("         )317h!#&([]  ")
        print("         rg234&*(*[]  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        E = V/2
        F = E*1500
        print("Your car was going at",V,"m/s. When your car hit the wall the force applied on the wall was",F,"Newtons. Due to Newton's 3rd law the wall exerted",F,"Newtons on your car. Crushing it.")
        print("Try started your brakes earlier.")
        print(" ")
        print("Read a book before getting behind a wheel.")
        sleep(10)
        clear()
    else:
        sleep(.05)
        clear()
        print("  _____           []  ")
        print(" [][] [|          []  ")
        print(" L______}         []  ")
        print(" Oo   oO          []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.05)
        clear()
        print("   _____          []  ")
        print("  [][] [|         []  ")
        print("  L______}        []  ")
        print("  Oo   oO         []  ")
        print("0m________________50m")
        sleep(.2)
        clear()
        print("     _____        []  ")
        print("    [][] [|       []  ")
        print("    L______}      []  ")
        print("    Oo   oO       []  ")
        print("0m________________50m")
        sleep(.25)
        clear()
        print("      _____       []  ")
        print("     [][] [|      []  ")
        print("     L______}     []  ")
        print("     Oo   oO      []  ")
        print("0m________________50m")
        sleep(.2)
        clear()
        print("       _____      []  ")
        print("      [][] [|     []  ")
        print("      L______}    []  ")
        print("      Oo   oO     []  ")
        print("0m________________50m")
        sleep(.25)
        clear()
        print("        _____     []  ")
        print("       [][] [|    []  ")
        print("       L______}   []  ")
        print("       Oo   oO    []  ")
        print("0m________________50m")
        sleep(.3)
        clear()
        print("         _____    []  ")
        print("        [][] [|   []  ")
        print("        L______}  []  ")
        print("        Oo   oO   []  ")
        print("0m________________50m")
        sleep(.4)
        clear()
        print("          _____   []  ")
        print("         [][] [|  []  ")
        print("         L______} []  ")
        print("         Oo   oO  []  ")
        print("0m________________50m")
        sleep(.5)
        clear()
        print("           _____  []  ")
        print("          [][] [| []  ")
        print("          L______}[]  ")
        print("          Oo   oO []  ")
        print("0m________________50m")
        print("Good job, your car came to a complete stop before killing yourself.")
        print("")
        print("Your the only one that is happy that you are alive.")
        sleep(10)





